
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    restart: always
    ports:
      - "20:20"
      - "2121:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data/:/home/vsftpd
    environment:
      FTP_USER: k88936
      FTP_PASS: 88888888
      PASV_ADDR_RESOLVE: YES
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
